basePath: /
info:
  contact: {}
  description: This is a sample shortener server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Swagger shortener API
  version: "1.0"
paths:
  /:
    post:
      consumes:
      - text/plain
      description: post long URL string
      parameters:
      - description: long URL
        in: body
        name: long_url
        required: true
        schema:
          type: string
      produces:
      - text/plain
      responses:
        "200":
          description: success
          schema:
            type: string
        "201":
          description: created
          schema:
            type: string
        "500":
          description: fail
          schema:
            type: string
      summary: post URL
      tags:
      - shortener
  /{key}:
    get:
      description: get short URL string
      parameters:
      - description: short URL
        in: path
        name: key
        required: true
        type: string
      produces:
      - text/plain
      responses:
        "200":
          description: success
          schema:
            type: string
        "404":
          description: not found
          schema:
            type: string
        "500":
          description: fail
          schema:
            type: string
      summary: get URL
      tags:
      - shortener
swagger: "2.0"
